// workspaces/vue/src/App.vue
<template>
		<div id="app">
			     <Button data-component class="btn">Go</Button>     <Img data-component class="image test" />
		</div>
	</template>

	<script>
	
import Button from "./components/button/index.vue";
import Img from "./components/img/index.vue";

	export default {
		name: 'App',
		components: {
			
	Button,
	Img,
		}
	}
	</script>

// workspaces/react/src/App.tsx
import "./App.css"; 
import Button from "./components/button";
import Carousel from "./components/carousel";
import Header from "./components/header";
import Img from "./components/img";

	function App() {
		return (
			<div className="App">
				
				<Button />
				<Carousel />
				<Header />
				<Img />
			</div>
		);
	}
	
	export default App;
